import { api } from '../lib/api'
import type { Patient, PatientHistory } from '../types'

export interface CreatePatientDto {
  fullName: string
  /** Auto-generated by the server — do not send */
  patientCode?: string
  age?: number
  dateOfBirth?: string
  gender?: string
  bloodGroup?: string
  email?: string
  phoneNumber?: string
  addressLine?: string
  city?: string
  state?: string
  postalCode?: string
  emergencyContactName?: string
  emergencyContactPhone?: string
  isB2b?: boolean
  b2bLabId?: number | null
  labBranchId?: number | null
  doctorName?: string
  reportDate?: string
}

export const patientService = {
  getAll: async (search?: string, page?: number, limit?: number): Promise<Patient[]> => {
    const params: Record<string, unknown> = {}
    if (search) params.search = search
    if (page) params.page = page
    if (limit) params.limit = limit
    const { data } = await api.get('/patients', { params })
    if (Array.isArray(data)) return data
    if (Array.isArray(data.data)) return data.data
    return []
  },

  getPaginated: async (search?: string, page = 1, limit = 20): Promise<{ data: Patient[]; total: number; page: number; limit: number }> => {
    const params: Record<string, unknown> = { page, limit }
    if (search) params.search = search
    const { data } = await api.get('/patients', { params })
    if (Array.isArray(data)) return { data, total: data.length, page: 1, limit: data.length }
    return { data: data.data ?? [], total: data.total ?? 0, page: data.page ?? 1, limit: data.limit ?? limit }
  },

  create: async (payload: CreatePatientDto): Promise<Patient> => {
    const { data } = await api.post('/patients', payload)
    return data
  },

  update: async (id: number, payload: Partial<CreatePatientDto>): Promise<Patient> => {
    const { data } = await api.patch(`/patients/${id}`, payload)
    return data
  },

  delete: async (id: number): Promise<void> => {
    await api.delete(`/patients/${id}`)
  },

  getById: async (id: number): Promise<Patient> => {
    const { data } = await api.get(`/patients/${id}`)
    return data
  },

  getHistory: async (patientId: number): Promise<PatientHistory> => {
    const { data } = await api.get(`/patients/${patientId}/results-history`)
    return data
  },
}
