import { useState, useEffect, useRef } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  ArrowLeft, Save, User, Phone, MapPin, AlertCircle, Building2,
  FlaskConical, CreditCard, Loader2, Upload, FileText, X,
  Paperclip, ChevronDown, Search, Stethoscope,
} from 'lucide-react'
import { Button } from '../components/ui/Button'
import { Input, Select } from '../components/ui/Input'
import { patientService, type CreatePatientDto } from '../services/patients'
import { b2bLabService } from '../services/b2bLabs'
import { labBranchService } from '../services/labBranches'
import { templateService } from '../services/templates'
import { orderService } from '../services/orders'
import { PageLoader } from '../components/ui/Spinner'
import { toast } from 'sonner'

const GENDERS = ['Male', 'Female', 'Other', 'Prefer not to say']
const DISCOUNT_OPTIONS = [0, 5, 10, 15, 20, 25, 30, 50]

interface PatientFormState extends Omit<CreatePatientDto, 'age' | 'isB2b' | 'b2bLabId' | 'labBranchId' | 'patientCode'> {
  age: string
  isB2b: boolean
  b2bLabId: string
  labBranchId: string
}

const emptyForm: PatientFormState = {
  fullName: '', age: '', dateOfBirth: '',
  gender: '', email: '', phoneNumber: '',
  addressLine: '', city: '', state: '', postalCode: '',
  emergencyContactName: '', emergencyContactPhone: '',
  isB2b: false, b2bLabId: '', labBranchId: '',
  doctorName: '', reportDate: new Date().toISOString().split('T')[0],
}

function patientToForm(p: import('../types').Patient): PatientFormState {
  return {
    fullName: p.fullName ?? '',
    age: p.age != null ? String(p.age) : '', dateOfBirth: p.dateOfBirth ?? '',
    gender: p.gender ?? '',
    email: p.email ?? '', phoneNumber: p.phoneNumber ?? '',
    addressLine: p.addressLine ?? '', city: p.city ?? '',
    state: p.state ?? '', postalCode: p.postalCode ?? '',
    emergencyContactName: p.emergencyContactName ?? '',
    emergencyContactPhone: p.emergencyContactPhone ?? '',
    isB2b: p.isB2b ?? false,
    b2bLabId: p.b2bLabId != null ? String(p.b2bLabId) : '',
    labBranchId: p.labBranchId != null ? String(p.labBranchId) : '',
    doctorName: p.doctorName ?? '',
    reportDate: p.reportDate ?? new Date().toISOString().split('T')[0],
  }
}

function formToDto(form: PatientFormState): CreatePatientDto {
  return {
    fullName: form.fullName,
    // patientCode is auto-generated by the server
    age: form.age ? Number(form.age) : undefined,
    dateOfBirth: form.dateOfBirth || undefined,
    gender: form.gender || undefined,
    email: form.email || undefined,
    phoneNumber: form.phoneNumber || undefined,
    addressLine: form.addressLine || undefined,
    city: form.city || undefined,
    state: form.state || undefined,
    postalCode: form.postalCode || undefined,
    emergencyContactName: form.emergencyContactName || undefined,
    emergencyContactPhone: form.emergencyContactPhone || undefined,
    isB2b: form.isB2b,
    b2bLabId: form.b2bLabId ? Number(form.b2bLabId) : null,
    labBranchId: form.labBranchId ? Number(form.labBranchId) : null,
    doctorName: form.doctorName || undefined,
    reportDate: form.reportDate || undefined,
  }
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function getFileIcon(fileName: string) {
  const ext = fileName.split('.').pop()?.toLowerCase()
  if (ext === 'pdf') return '📄'
  if (['jpg', 'jpeg', 'png', 'gif', 'webp'].includes(ext ?? '')) return '🖼️'
  if (['doc', 'docx'].includes(ext ?? '')) return '📝'
  return '📎'
}

interface DocumentEntry {
  id: string; name: string; file: File; url: string
}

function SectionTitle({ icon, title }: { icon: React.ReactNode; title: string }) {
  return (
    <div className="flex items-center gap-2 mb-4">
      <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-100 text-indigo-600">{icon}</div>
      <h3 className="text-sm font-bold uppercase tracking-wide text-slate-600">{title}</h3>
    </div>
  )
}

function FormCard({ children }: { children: React.ReactNode }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{children}</div>
}

export default function PatientFormPage() {
  const { id } = useParams<{ id?: string }>()
  const isEdit = !!id
  const navigate = useNavigate()
  const qc = useQueryClient()

  const [form, setForm] = useState<PatientFormState>(emptyForm)
  const [selectedTests, setSelectedTests] = useState<Array<{ templateId: number }>>([])
  const [discount, setDiscount] = useState(0)
  const [paymentStatus, setPaymentStatus] = useState<'PENDING' | 'PAID' | 'PARTIAL'>('PENDING')
  const [paymentType, setPaymentType] = useState<'CASH' | 'CHEQUE' | 'ONLINE'>('CASH')

  // Test dropdown state
  const [testDropdownOpen, setTestDropdownOpen] = useState(false)
  const [testSearch, setTestSearch] = useState('')
  const testDropdownRef = useRef<HTMLDivElement>(null)

  // Document upload state
  const [documents, setDocuments] = useState<DocumentEntry[]>([])
  const [pendingFile, setPendingFile] = useState<{ file: File; name: string } | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  // Lookups
  const { data: b2bLabs = [] } = useQuery({ queryKey: ['b2b-labs'], queryFn: b2bLabService.getAll })
  const { data: labBranches = [] } = useQuery({ queryKey: ['lab-branches'], queryFn: labBranchService.getAll })
  const { data: allTemplates = [] } = useQuery({ queryKey: ['templates'], queryFn: templateService.getAll })
  const activeTemplates = allTemplates.filter(t => t.active)

  // Load existing patient when editing
  const { data: existingPatient, isLoading: loadingPatient } = useQuery({
    queryKey: ['patient', id],
    queryFn: () => patientService.getById(Number(id)),
    enabled: isEdit,
  })

  useEffect(() => {
    if (existingPatient) setForm(patientToForm(existingPatient))
  }, [existingPatient])

  // Close test dropdown on outside click
  useEffect(() => {
    if (!testDropdownOpen) return
    const handler = (e: MouseEvent) => {
      if (testDropdownRef.current && !testDropdownRef.current.contains(e.target as Node)) {
        setTestDropdownOpen(false)
        setTestSearch('')
      }
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [testDropdownOpen])

  // Cleanup object URLs on unmount
  useEffect(() => {
    return () => { documents.forEach(d => URL.revokeObjectURL(d.url)) }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const setField = (key: keyof PatientFormState) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
      setForm(p => ({ ...p, [key]: e.target.value }))

  // ── Test helpers ────────────────────────────────────────────────────────────
  const toggleTest = (templateId: number) =>
    setSelectedTests(prev =>
      prev.find(t => t.templateId === templateId)
        ? prev.filter(t => t.templateId !== templateId)
        : [...prev, { templateId }]
    )

  const getTestPrice = (tmpl: typeof activeTemplates[0]): number => {
    if (form.isB2b && form.b2bLabId) {
      const b2bPrice = tmpl.b2bPrices?.find(p => p.b2bLabId === Number(form.b2bLabId))
      if (b2bPrice) return Number(b2bPrice.amount)
    }
    return Number(tmpl.amount)
  }

  const filteredTemplatesForDropdown = activeTemplates.filter(t =>
    t.name.toLowerCase().includes(testSearch.toLowerCase()) ||
    t.code.toLowerCase().includes(testSearch.toLowerCase())
  )

  const subtotal = selectedTests.reduce((sum, sel) => {
    const tmpl = activeTemplates.find(t => t.id === sel.templateId)
    return sum + (tmpl ? getTestPrice(tmpl) : 0)
  }, 0)
  const discountAmt = Math.round(subtotal * discount / 100)
  const netAmount = subtotal - discountAmt

  // ── Document helpers ────────────────────────────────────────────────────────
  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    setPendingFile({ file, name: file.name.replace(/\.[^/.]+$/, '') })
    e.target.value = ''
  }

  const confirmAddDocument = () => {
    if (!pendingFile) return
    setDocuments(prev => [...prev, {
      id: `${Date.now()}-${Math.random()}`,
      name: pendingFile.name.trim() || pendingFile.file.name,
      file: pendingFile.file,
      url: URL.createObjectURL(pendingFile.file),
    }])
    setPendingFile(null)
  }

  const removeDocument = (docId: string) => {
    setDocuments(prev => {
      const doc = prev.find(d => d.id === docId)
      if (doc) URL.revokeObjectURL(doc.url)
      return prev.filter(d => d.id !== docId)
    })
  }

  // ── Mutations ───────────────────────────────────────────────────────────────
  const createMutation = useMutation({
    mutationFn: async () => {
      const patient = await patientService.create(formToDto(form))
      if (selectedTests.length > 0) {
        const result = await orderService.createBatch({
          patientId: patient.id,
          orders: selectedTests.map(s => ({ templateId: s.templateId })),
          discount, paymentStatus, paymentType,
        })
        toast.success(`Patient registered · ${selectedTests.length} test(s) · Receipt: ${result.receiptNumber}`)
      } else {
        toast.success('Patient profile created')
      }
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['patients'] })
      qc.invalidateQueries({ queryKey: ['orders'] })
      navigate('/patients')
    },
    onError: (err: unknown) =>
      toast.error((err as { response?: { data?: { message?: string } } })?.response?.data?.message || 'Failed to save patient'),
  })

  const updateMutation = useMutation({
    mutationFn: () => patientService.update(Number(id), formToDto(form)),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['patients'] })
      qc.invalidateQueries({ queryKey: ['patient', id] })
      toast.success('Patient updated')
      navigate('/patients')
    },
    onError: (err: unknown) =>
      toast.error((err as { response?: { data?: { message?: string } } })?.response?.data?.message || 'Failed to update patient'),
  })

  const handleSave = () => {
    if (!form.fullName.trim()) {
      toast.error('Full name is required')
      return
    }
    isEdit ? updateMutation.mutate() : createMutation.mutate()
  }

  const isPending = createMutation.isPending || updateMutation.isPending

  if (isEdit && loadingPatient) return <PageLoader />

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Top bar */}
      <div className="sticky top-0 z-10 border-b border-slate-200 bg-white px-6 py-4 flex items-center justify-between shadow-sm">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/patients')}
            className="flex h-9 w-9 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-500 hover:bg-slate-50 hover:text-slate-700 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
          </button>
          <div>
            <h1 className="text-lg font-bold text-slate-900">
              {isEdit ? `Edit Patient — ${existingPatient?.fullName ?? ''}` : 'Register New Patient'}
            </h1>
            <p className="text-xs text-slate-400">
              {isEdit ? 'Update patient information' : 'Create a comprehensive patient profile'}
            </p>
          </div>
        </div>
        <Button
          icon={isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
          loading={isPending}
          onClick={handleSave}
        >
          {isEdit ? 'Save Changes' : 'Register Patient'}
        </Button>
      </div>

      <div className="mx-auto max-w-5xl px-6 py-8 space-y-6">

        {/* ── 1. Referral & Visit (B2B section — FIRST) ── */}
        <FormCard>
          <SectionTitle icon={<Building2 className="h-4 w-4" />} title="Referral & Visit Details" />
          <div className="space-y-5">
            {/* B2B toggle */}
            <div className="flex gap-6">
              <label className="flex items-center gap-2.5 cursor-pointer">
                <input type="radio" checked={!form.isB2b}
                  onChange={() => setForm(p => ({ ...p, isB2b: false, b2bLabId: '' }))}
                  className="h-4 w-4 accent-indigo-600" />
                <span className="text-sm font-medium text-slate-700">Individual Patient</span>
              </label>
              <label className="flex items-center gap-2.5 cursor-pointer">
                <input type="radio" checked={form.isB2b}
                  onChange={() => setForm(p => ({ ...p, isB2b: true }))}
                  className="h-4 w-4 accent-indigo-600" />
                <span className="text-sm font-medium text-slate-700">B2B Referral</span>
              </label>
            </div>

            {form.isB2b && (
              <Select label="B2B Lab Partner" value={form.b2bLabId}
                onChange={e => setForm(p => ({ ...p, b2bLabId: e.target.value }))}>
                <option value="">Select B2B lab</option>
                {b2bLabs.filter(l => l.active).map(l => <option key={l.id} value={l.id}>{l.name}</option>)}
              </Select>
            )}

            <div className="grid gap-4 sm:grid-cols-2">
              <Select label="Our Branch (Optional)" value={form.labBranchId}
                onChange={e => setForm(p => ({ ...p, labBranchId: e.target.value }))}>
                <option value="">Select branch</option>
                {labBranches.filter(b => b.active).map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
              </Select>
              <Input label="Report Date" type="date"
                value={form.reportDate ?? ''} onChange={setField('reportDate')} />
            </div>
          </div>
        </FormCard>

        {/* ── 2. Basic Information ── */}
        <FormCard>
          <SectionTitle icon={<User className="h-4 w-4" />} title="Basic Information" />
          {isEdit && existingPatient?.patientCode && (
            <div className="mb-4 flex items-center gap-3 rounded-xl border border-indigo-100 bg-indigo-50 px-4 py-3">
              <span className="text-xs font-semibold uppercase tracking-wide text-indigo-500">Patient Code</span>
              <span className="font-mono text-sm font-bold text-indigo-700">{existingPatient.patientCode}</span>
              <span className="ml-auto text-xs text-indigo-400">Auto-generated · read-only</span>
            </div>
          )}
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <Input label="Full Name" placeholder="John Doe" value={form.fullName} onChange={setField('fullName')} required />
            <Input label="Age" type="number" placeholder="25" value={form.age} onChange={setField('age')} />
            <Input label="Date of Birth" type="date" value={form.dateOfBirth} onChange={setField('dateOfBirth')} />
            <Select label="Gender" value={form.gender} onChange={setField('gender')}>
              <option value="">Select gender</option>
              {GENDERS.map(g => <option key={g} value={g}>{g}</option>)}
            </Select>
          </div>
        </FormCard>

        {/* ── 3. Contact ── */}
        <FormCard>
          <SectionTitle icon={<Phone className="h-4 w-4" />} title="Contact Information" />
          <div className="grid gap-4 sm:grid-cols-2">
            <Input label="Email" type="email" placeholder="patient@email.com" value={form.email} onChange={setField('email')} />
            <Input label="Phone Number" placeholder="+91 98765 43210" value={form.phoneNumber} onChange={setField('phoneNumber')} />
          </div>
        </FormCard>

        {/* ── 4. Address ── */}
        <FormCard>
          <SectionTitle icon={<MapPin className="h-4 w-4" />} title="Address" />
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="sm:col-span-2">
              <Input label="Address Line" placeholder="123 Main Street" value={form.addressLine} onChange={setField('addressLine')} />
            </div>
            <Input label="City" placeholder="Mumbai" value={form.city} onChange={setField('city')} />
            <Input label="State" placeholder="Maharashtra" value={form.state} onChange={setField('state')} />
            <Input label="Postal Code" placeholder="400001" value={form.postalCode} onChange={setField('postalCode')} />
          </div>
        </FormCard>

        {/* ── 5. Emergency Contact ── */}
        <FormCard>
          <SectionTitle icon={<AlertCircle className="h-4 w-4" />} title="Emergency Contact" />
          <div className="grid gap-4 sm:grid-cols-2">
            <Input label="Contact Name" placeholder="Jane Doe" value={form.emergencyContactName} onChange={setField('emergencyContactName')} />
            <Input label="Contact Phone" placeholder="+91 98765 43210" value={form.emergencyContactPhone} onChange={setField('emergencyContactPhone')} />
          </div>
        </FormCard>

        {/* ── 6. Documents ── */}
        <FormCard>
          <SectionTitle icon={<Paperclip className="h-4 w-4" />} title="Documents" />

          <input ref={fileInputRef} type="file" className="hidden"
            accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.gif,.webp"
            onChange={handleFileSelect} />

          {documents.length > 0 && (
            <div className="mb-4 space-y-2">
              {documents.map(doc => (
                <div key={doc.id}
                  className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 hover:border-indigo-200 hover:bg-indigo-50/40 transition-colors">
                  <a href={doc.url} target="_blank" rel="noopener noreferrer"
                    className="flex min-w-0 flex-1 items-center gap-3 group" title={`Open ${doc.name}`}>
                    <span className="text-xl leading-none select-none">{getFileIcon(doc.file.name)}</span>
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm font-semibold text-slate-800 group-hover:text-indigo-600 transition-colors">{doc.name}</p>
                      <p className="truncate text-xs text-slate-400">{doc.file.name} · {formatBytes(doc.file.size)}</p>
                    </div>
                    <FileText className="h-4 w-4 shrink-0 text-slate-300 group-hover:text-indigo-400 transition-colors" />
                  </a>
                  <button onClick={() => removeDocument(doc.id)}
                    className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg text-slate-400 hover:bg-rose-100 hover:text-rose-500 transition-colors"
                    title="Remove">
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
              ))}
            </div>
          )}

          {pendingFile ? (
            <div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4">
              <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-indigo-600">Name this document</p>
              <div className="flex items-center gap-3">
                <span className="text-xl leading-none">{getFileIcon(pendingFile.file.name)}</span>
                <input autoFocus type="text" value={pendingFile.name}
                  onChange={e => setPendingFile(p => p ? { ...p, name: e.target.value } : null)}
                  onKeyDown={e => { if (e.key === 'Enter') confirmAddDocument(); if (e.key === 'Escape') setPendingFile(null) }}
                  placeholder="Document name"
                  className="flex-1 rounded-xl border border-indigo-300 bg-white px-3 py-2 text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" />
                <button onClick={confirmAddDocument}
                  className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700 transition-colors">Add</button>
                <button onClick={() => setPendingFile(null)}
                  className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 transition-colors">Cancel</button>
              </div>
              <p className="mt-2 text-xs text-indigo-500">{pendingFile.file.name} · {formatBytes(pendingFile.file.size)}</p>
            </div>
          ) : (
            <button onClick={() => fileInputRef.current?.click()}
              className="flex w-full items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-200 bg-white py-4 text-sm font-medium text-slate-500 transition-all hover:border-indigo-300 hover:bg-indigo-50/40 hover:text-indigo-600">
              <Upload className="h-4 w-4" />
              Upload Document
            </button>
          )}

          {documents.length === 0 && !pendingFile && (
            <p className="mt-2 text-center text-xs text-slate-400">PDF, JPG, PNG, Word · Click a document to open it</p>
          )}
        </FormCard>

        {/* ── 7. Test Selection — dropdown, only on create ── */}
        {!isEdit && activeTemplates.length > 0 && (
          <FormCard>
            <SectionTitle icon={<FlaskConical className="h-4 w-4" />} title="Test Selection" />

            {/* Dropdown trigger */}
            <div ref={testDropdownRef} className="relative">
              <button
                type="button"
                onClick={() => setTestDropdownOpen(o => !o)}
                className="flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600 transition-all hover:border-indigo-300 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"
              >
                <span className={selectedTests.length === 0 ? 'text-slate-400' : 'font-medium text-slate-700'}>
                  {selectedTests.length === 0
                    ? 'Click to select tests…'
                    : `${selectedTests.length} test${selectedTests.length !== 1 ? 's' : ''} selected`}
                </span>
                <ChevronDown className={`h-4 w-4 text-slate-400 transition-transform ${testDropdownOpen ? 'rotate-180' : ''}`} />
              </button>

              {testDropdownOpen && (
                <div className="absolute left-0 right-0 top-full z-20 mt-1 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">
                  {/* Search inside dropdown */}
                  <div className="border-b border-slate-100 px-3 py-2">
                    <div className="relative">
                      <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" />
                      <input
                        autoFocus
                        type="text"
                        value={testSearch}
                        onChange={e => setTestSearch(e.target.value)}
                        placeholder="Search tests…"
                        className="w-full rounded-lg bg-slate-50 py-1.5 pl-8 pr-3 text-sm outline-none focus:bg-white focus:ring-1 focus:ring-indigo-200"
                      />
                    </div>
                  </div>

                  {/* Options list */}
                  <div className="max-h-60 overflow-y-auto">
                    {filteredTemplatesForDropdown.length === 0 ? (
                      <p className="px-4 py-3 text-sm text-slate-400">No tests found</p>
                    ) : filteredTemplatesForDropdown.map(tmpl => {
                      const isSelected = !!selectedTests.find(t => t.templateId === tmpl.id)
                      const price = getTestPrice(tmpl)
                      return (
                        <div
                          key={tmpl.id}
                          onClick={() => toggleTest(tmpl.id)}
                          className={`flex cursor-pointer items-center gap-3 px-4 py-2.5 transition-colors hover:bg-slate-50 ${isSelected ? 'bg-indigo-50/60' : ''}`}
                        >
                          <div className={`flex h-4 w-4 shrink-0 items-center justify-center rounded border-2 transition-colors ${
                            isSelected ? 'border-indigo-600 bg-indigo-600' : 'border-slate-300'
                          }`}>
                            {isSelected && (
                              <svg className="h-2.5 w-2.5 text-white" fill="none" viewBox="0 0 12 12">
                                <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                              </svg>
                            )}
                          </div>
                          <div className="flex-1 min-w-0">
                            <span className={`text-sm ${isSelected ? 'font-semibold text-indigo-700' : 'text-slate-700'}`}>{tmpl.name}</span>
                            <span className="ml-2 text-xs font-mono text-slate-400">{tmpl.code}</span>
                          </div>
                          <span className="shrink-0 text-xs font-semibold text-indigo-600">
                            {price > 0 ? `₹${price.toLocaleString()}` : '—'}
                          </span>
                        </div>
                      )
                    })}
                  </div>

                  {/* Footer */}
                  <div className="border-t border-slate-100 px-4 py-2 flex justify-between items-center bg-slate-50">
                    <span className="text-xs text-slate-400">
                      {selectedTests.length} of {activeTemplates.length} selected
                    </span>
                    <button
                      onClick={() => { setTestDropdownOpen(false); setTestSearch('') }}
                      className="text-xs font-semibold text-indigo-600 hover:underline"
                    >
                      Done
                    </button>
                  </div>
                </div>
              )}
            </div>

            {/* Selected tests summary list */}
            {selectedTests.length > 0 && (
              <div className="mt-3 space-y-1.5">
                {selectedTests.map(sel => {
                  const tmpl = activeTemplates.find(t => t.id === sel.templateId)
                  if (!tmpl) return null
                  const price = getTestPrice(tmpl)
                  return (
                    <div key={sel.templateId}
                      className="flex items-center justify-between rounded-xl bg-indigo-50 px-4 py-2.5">
                      <div className="flex items-center gap-2">
                        <FlaskConical className="h-3.5 w-3.5 text-indigo-400 shrink-0" />
                        <span className="text-sm font-medium text-indigo-800">{tmpl.name}</span>
                        <span className="text-xs font-mono text-indigo-400">{tmpl.code}</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <span className="text-sm font-semibold text-indigo-700">
                          {price > 0 ? `₹${price.toLocaleString()}` : '—'}
                        </span>
                        <button onClick={() => toggleTest(sel.templateId)}
                          className="flex h-5 w-5 items-center justify-center rounded-full text-indigo-400 hover:bg-indigo-200 hover:text-indigo-700 transition-colors">
                          <X className="h-3 w-3" />
                        </button>
                      </div>
                    </div>
                  )
                })}
                {/* Subtotal */}
                <div className="flex justify-between rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm">
                  <span className="text-slate-500">Subtotal</span>
                  <span className="font-bold text-slate-800">₹{subtotal.toLocaleString()}</span>
                </div>
              </div>
            )}
          </FormCard>
        )}

        {/* ── 8. Payment — only on create with tests selected ── */}
        {!isEdit && selectedTests.length > 0 && (
          <FormCard>
            <SectionTitle icon={<CreditCard className="h-4 w-4" />} title="Payment" />
            <div className="space-y-5">
              {/* Discount */}
              <div className="flex items-center gap-4">
                <label className="text-sm font-semibold text-slate-700 shrink-0">Discount:</label>
                <div className="flex gap-2 flex-wrap">
                  {DISCOUNT_OPTIONS.map(d => (
                    <button key={d} onClick={() => setDiscount(d)}
                      className={`rounded-lg border px-3 py-1.5 text-sm font-medium transition-all ${
                        discount === d
                          ? 'border-indigo-500 bg-indigo-600 text-white shadow-sm'
                          : 'border-slate-200 bg-white text-slate-600 hover:border-indigo-300 hover:text-indigo-600'
                      }`}>
                      {d}%
                    </button>
                  ))}
                </div>
              </div>

              {/* Amount breakdown */}
              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2.5 text-sm">
                <div className="flex justify-between text-slate-600">
                  <span>Subtotal</span><span>₹{subtotal.toLocaleString()}</span>
                </div>
                {discount > 0 && (
                  <div className="flex justify-between text-emerald-600">
                    <span>Discount ({discount}%)</span><span>− ₹{discountAmt.toLocaleString()}</span>
                  </div>
                )}
                <div className="flex justify-between font-bold text-slate-900 border-t border-slate-200 pt-2.5 text-base">
                  <span>Net Amount</span><span>₹{netAmount.toLocaleString()}</span>
                </div>
              </div>

              {/* Payment type & status */}
              <div className="grid gap-6 sm:grid-cols-2">
                <div>
                  <p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Payment Method</p>
                  <div className="flex gap-3 flex-wrap">
                    {(['CASH', 'CHEQUE', 'ONLINE'] as const).map(pt => (
                      <label key={pt} className={`flex items-center gap-2 cursor-pointer rounded-xl border px-3 py-2 transition-all ${
                        paymentType === pt ? 'border-indigo-400 bg-indigo-50 text-indigo-700' : 'border-slate-200 bg-white text-slate-600 hover:border-indigo-200'
                      }`}>
                        <input type="radio" checked={paymentType === pt}
                          onChange={() => setPaymentType(pt)} className="h-4 w-4 accent-indigo-600" />
                        <span className="text-sm font-medium capitalize">{pt.toLowerCase()}</span>
                      </label>
                    ))}
                  </div>
                </div>
                <div>
                  <p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Payment Status</p>
                  <div className="flex gap-3 flex-wrap">
                    {([
                      { value: 'PAID', color: 'emerald' },
                      { value: 'PENDING', color: 'amber' },
                      { value: 'PARTIAL', color: 'blue' },
                    ] as const).map(({ value: ps, color }) => (
                      <label key={ps} className={`flex items-center gap-2 cursor-pointer rounded-xl border px-3 py-2 transition-all ${
                        paymentStatus === ps
                          ? `border-${color}-400 bg-${color}-50 text-${color}-700`
                          : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'
                      }`}>
                        <input type="radio" checked={paymentStatus === ps}
                          onChange={() => setPaymentStatus(ps)} className="h-4 w-4 accent-indigo-600" />
                        <span className="text-sm font-medium capitalize">{ps.toLowerCase()}</span>
                      </label>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </FormCard>
        )}

        {/* ── 9. Doctor Name — LAST ── */}
        <FormCard>
          <SectionTitle icon={<Stethoscope className="h-4 w-4" />} title="Referring Doctor" />
          <div className="max-w-sm">
            <Input
              label="Doctor Name"
              placeholder="Dr. Name"
              value={form.doctorName ?? ''}
              onChange={setField('doctorName')}
            />
          </div>
        </FormCard>

        {/* Bottom save button */}
        <div className="flex justify-end gap-3 pb-8">
          <button
            onClick={() => navigate('/patients')}
            className="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-medium text-slate-600 hover:bg-slate-50 transition-colors"
          >
            Cancel
          </button>
          <Button
            icon={isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
            loading={isPending}
            onClick={handleSave}
          >
            {isEdit ? 'Save Changes' : 'Register Patient'}
          </Button>
        </div>
      </div>
    </div>
  )
}
